version: '3.8'

services:

  catalog-server:
    container_name: catalog
    build:
      context: .
      target: production
    volumes:
      - ./src/catalog-service:/app/src/catalog-service:ro
      - ./src/nginx:/app/src/nginx:ro
      - ./src/catalog-service/database.db:/app/database.db:rw
    ports:
      - '3005:3005'
    environment:
      - PORT=3005
      - NODE_ENV=production

  catalog-replica:
    container_name: catalog-replica
    build:
      context: .
      target: production2
    volumes:
      - ./src/catalog-service-replica:/app/src/catalog-service-replica:ro
      - ./src/nginx:/app/src/nginx:ro
      - ./src/catalog-service-replica/database.db:/app/database.db:rw
    ports:
      - '3009:3009'
    environment:
      - PORT=3009
      - NODE_ENV=production2

  order-server:
    container_name: order
    build:
      context: .
      target: production1
    volumes:
      - ./src/order-service:/app/src/order-service:ro
      - ./src/nginx:/app/src/nginx:ro
    ports:
      - '3006:3006'
    environment:
      - PORT=3006
      - NODE_ENV=production1

  order-replica:
    container_name: order-replica
    build:
      context: .
      target: production3
    volumes:
      - ./src/order-service-replica:/app/src/order-service-replica:ro
      - ./src/nginx:/app/src/nginx:ro
    ports:
      - '3008:3008'
    environment:
      - PORT=3008
      - NODE_ENV=production3

  client:
    container_name: client
    build:
      context: .
    volumes:
      - ./src/client-service:/app/src/client-service:ro
    ports:
      - '3007:3007'

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8083:80'
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - catalog-server
      - catalog-replica
      - order-server
      - order-replica
      - client

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
